### ISSUE TITLE
Incompatible avec Windows?

### ISSUE THREAD

**Issue by immjs** [N-igma/Opacq#5]
Erreur:
```
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\infor\Opacq\tcp_broadcast.py", line 50, in run
    data, sender = cs.recvfrom(4)
                   ^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

Cette erreur semble spécifique à Windows

**Comment by immjs** [comment]
Réparé PR #6
